<?php
require_once '../includes/functions.php';
require_once '../includes/auth_helper.php';

// Redirect ke login jika belum login
if (!isLoggedIn()) {
    die('Access denied!');
}

// Admin dan HRD Admin bisa akses
if (!isAdmin() && !isHRDAdmin()) {
    die('Access denied!');
}

if (!isset($_GET['file'])) {
    die('File not specified!');
}

$filename = sanitize($_GET['file']);
$filepath = __DIR__ . '/backups/' . $filename;

if (!file_exists($filepath)) {
    die('File not found!');
}

// Baca header file untuk mendapatkan informasi
$content = file_get_contents($filepath, false, null, 0, 5000);
$first_lines = explode("\n", $content, 20);

// Ekstrak informasi
$info = [
    'filename' => $filename,
    'size' => formatSize(filesize($filepath)),
    'modified' => date('Y-m-d H:i:s', filemtime($filepath)),
    'lines' => count(file($filepath)),
    'tables' => [],
    'backup_date' => '',
    'generated_by' => ''
];

// Parse informasi dari header
foreach ($first_lines as $line) {
    if (strpos($line, '-- Date:') !== false) {
        $info['backup_date'] = trim(str_replace('-- Date:', '', $line));
    }
    if (strpos($line, '-- Generated by:') !== false) {
        $info['generated_by'] = trim(str_replace('-- Generated by:', '', $line));
    }
    if (strpos($line, '-- Tables:') !== false) {
        $info['tables_list'] = trim(str_replace('-- Tables:', '', $line));
    }
}

// Hitung jumlah tabel
$pattern = '/CREATE TABLE `([^`]+)`/';
preg_match_all($pattern, $content, $matches);
$info['tables'] = $matches[1] ?? [];
$info['tables_count'] = count($info['tables']);

// Hitung jumlah baris data
$insert_pattern = '/INSERT INTO `[^`]+` VALUES/';
preg_match_all($insert_pattern, $content, $insert_matches);
$info['insert_statements'] = count($insert_matches[0]);

function formatSize($bytes) {
    $units = ['B', 'KB', 'MB', 'GB', 'TB'];
    $i = 0;
    while ($bytes >= 1024 && $i < count($units) - 1) {
        $bytes /= 1024;
        $i++;
    }
    return round($bytes, 2) . ' ' . $units[$i];
}
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <h5>Informasi File Backup</h5>
            <hr>
            
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-sm">
                        <tr>
                            <th width="40%">Nama File:</th>
                            <td><code><?php echo $info['filename']; ?></code></td>
                        </tr>
                        <tr>
                            <th>Ukuran File:</th>
                            <td><strong><?php echo $info['size']; ?></strong></td>
                        </tr>
                        <tr>
                            <th>Dimodifikasi:</th>
                            <td><?php echo $info['modified']; ?></td>
                        </tr>
                        <tr>
                            <th>Jumlah Baris:</th>
                            <td><span class="badge bg-primary"><?php echo number_format($info['lines']); ?> lines</span></td>
                        </tr>
                    </table>
                </div>
                
                <div class="col-md-6">
                    <table class="table table-sm">
                        <tr>
                            <th width="40%">Tanggal Backup:</th>
                            <td><?php echo $info['backup_date']; ?></td>
                        </tr>
                        <tr>
                            <th>Dibuat Oleh:</th>
                            <td><?php echo $info['generated_by']; ?></td>
                        </tr>
                        <tr>
                            <th>Jumlah Tabel:</th>
                            <td><span class="badge bg-success"><?php echo $info['tables_count']; ?> tables</span></td>
                        </tr>
                        <tr>
                            <th>INSERT Statements:</th>
                            <td><span class="badge bg-info"><?php echo number_format($info['insert_statements']); ?></span></td>
                        </tr>
                    </table>
                </div>
            </div>
            
            <?php if (!empty($info['tables_list'])): ?>
                <div class="mt-3">
                    <h6>Tabel yang Di-backup:</h6>
                    <div class="alert alert-secondary">
                        <?php echo $info['tables_list']; ?>
                    </div>
                </div>
            <?php endif; ?>
            
            <?php if (!empty($info['tables'])): ?>
                <div class="mt-3">
                    <h6>Daftar Tabel:</h6>
                    <div class="row">
                        <?php foreach ($info['tables'] as $table): ?>
                            <div class="col-md-3 mb-2">
                                <span class="badge bg-light text-dark border">
                                    <i class="fas fa-table me-1"></i><?php echo $table; ?>
                                </span>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
            
            <div class="mt-4">
                <h6>Preview Konten:</h6>
                <div class="border rounded p-3 bg-light" style="max-height: 300px; overflow-y: auto;">
                    <pre class="mb-0" style="font-size: 12px;"><?php 
                    $preview = implode("\n", array_slice($first_lines, 0, 30));
                    echo htmlspecialchars($preview);
                    if (count($first_lines) > 30) {
                        echo "\n\n... (file terlalu panjang untuk ditampilkan)";
                    }
                    ?></pre>
                </div>
            </div>
            
            <div class="mt-4 alert alert-info">
                <i class="fas fa-info-circle me-2"></i>
                File ini dapat digunakan untuk restore database atau diunduh untuk keperluan arsip.
            </div>
        </div>
    </div>
</div>